//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logoped.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogopedCabEntities1 : DbContext
    {
        public static LogopedCabEntities1 _context;  //присвоение значения контекста для будущего взаимодействия с базой данных
        public LogopedCabEntities1()
            : base("name=LogopedCabEntities1")
        {
        }
    public static LogopedCabEntities1 GetContext()
        {
            if (_context == null)
                _context = new LogopedCabEntities1();
                return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Raspisanie> Raspisanies { get; set; }
        public virtual DbSet<RechevayKarta> RechevayKartas { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
